# Python Basics



The goal of this notebook is to provide students with knowledge of the fundamentals of python. We will take a more interactive approach than most class room settings and ask the students to do some research on their own then bring their learnings back here to share with the class. 

### Variables

Variables work by assigning a value to a specific word or string of characters. It can be done using the "=" sign. This assigns whatever is on the right the string of characters on the left. We'll go ahead and try assigning a few variables in the next block.

In [1]:
a = 1
b = 2
c = 3
print(a,b,c) # when you put a variable by itself, its value will be printed (This is a comment - anything after a # on the same line will be ignored)

1 2 3


We can also perform basic algebra to these variables and save the output to a new variable

In [2]:
d = a + b
d

3

In [3]:
e = d - a
e

2

In [4]:
f = b * c
f

6

In [5]:
g = a / b
g

0.5

Sometimes we want to update the value of one variable, so we can do this

In [6]:
g = g*2 # the same thing works for /, +, and -
g

1.0

In [7]:
g*=3

In [8]:
g

3.0

This can get quite annoying with longer variable names, so we can do the following

In [9]:
f = f / 3

In [10]:
f/=2 # there is also +=, -=, and *=
f

1.0

There are tons of different types of variables we can make. For this next section, we will ask the students to go out and figure out how to create the following types of variable: strings, floats and booleans. Once you have created these variables, try the same operations we used above and see what they do.

Create a few string variables here, then try to add them together, subtract them, multiply them and divide them to see what happens. You may get an error, and thats okay. Its important to know what can and can't be done with a type of data.



In [11]:
## Dhruv and Nolawi


In [12]:
bob="chicken"
log="3"
chug="six"
bulb=3

In [13]:
print(bob+" "+log)

chicken 3


In [14]:
print(bob*3)

chickenchickenchicken


In [15]:
print(log*6)

333333


In [16]:
chicken=(((bob*log)/(log+bob)*dog))

TypeError: can't multiply sequence by non-int of type 'str'

In [17]:
print(chicken*chug)

NameError: name 'chicken' is not defined

In [18]:
print(bulb/0)

ZeroDivisionError: division by zero

Create a few float variables here, then try to add them together, subtract them, multiply them and divide them to see what happens. You may get an error, and thats okay. Its important to know what can and can't be done with a type of data.

In [19]:
## Holly and Jayden`


In [20]:
z = 0.5
x = 4.5
y = 0.6

In [21]:
w = x / z
w               b   

SyntaxError: invalid syntax (<ipython-input-21-363bb2315b39>, line 2)

In [22]:
t=z*x
t

2.25

In [23]:
s=x*y-z
s

2.1999999999999997

Create a few boolean variables here, then try to add them together, subtract them, multiply them and divide them to see what happens. You may get an error, and thats okay. Its important to know what can and can't be done with a type of data.



In [24]:
## Dhrupadh and Matthew

In [25]:
rat = True
dog = True
cat = False

In [26]:
fish = cat + rat + 5
fish

6

In [27]:
chicken = cat*2
print(chicken)

0


In [28]:
turtle = cat+cat
turtle

0

In [29]:
cat*rat*3

0

In [30]:
chickfila = cat + turtle
chickfila

0

In [31]:
innout = fish*3
innout

18

In [32]:
wendys = cat - rat
wendys

-1

In [33]:
arbys = dog * rat
arbys

1

In [34]:
print('True + True = ',True+True)
print('False + False = ',False+False)
print('True + False = ',True+False)
print('False + True = ',False+True)
tree = 5
tree/=False
tree


True + True =  2
False + False =  0
True + False =  1
False + True =  1


ZeroDivisionError: division by zero

### Lists



Lists work similarly to the variables we created above but store multiple values. We'll cover the three types metioned above then ask the students to try and create their own versions of them.



First up, lists. you can create a list with the following code.



In [35]:
my_list = [1, 2, 3, 4, 5]

To access a specific item from the list, you would do the following.



In [36]:
my_list[2] # here, 2 is the index you are accessing

3

The first element in the list is at index 0, then the second element is at index 1 and so on.



In [37]:
print(my_list[0], my_list[1], my_list[2], my_list[3], my_list[4])

1 2 3 4 5


**TODO:** Now its your turn. We will have students create their own version of this data type.



Below, create a list of your favorite colors. 



In [38]:
#create a list of your favorite colors


In [39]:
# Jayden
Jayden_list= ["red", "blue", "white"]

print(Jayden_list[2])

white


In [40]:
# Dhruv
Dhruv_list=["gold","black","red"]

print(Dhruv_list[0])

gold


In [41]:
# Holly
holly_list = ["green", "pink", "yellow"]

print(holly_list[0])

green


In [42]:
# Dhrupadh
color_list = ["blue", "red", "green", "white","Black"]

color_list[3]

'white'

In [43]:
# Matthew
Matthew_list = ["blue", "black", "white"]
print(Matthew_list[0])

blue


Now figure out how to `append()` an item to your list. Maybe google: "how to append an item to a list python"



In [44]:
# append another color to the list of your favorite colors


In [45]:
# Jayden
Jayden_list.append("gray")
print(Jayden_list)


['red', 'blue', 'white', 'gray']


In [46]:
# Dhruv

Dhruv_list.append("blue")
print(Dhruv_list)

['gold', 'black', 'red', 'blue']


In [47]:
# Holly
holly_list.append("red")
print(holly_list)

['green', 'pink', 'yellow', 'red']


In [48]:
# Dhrupadh
color_list.append("orange")
print(color_list)



['blue', 'red', 'green', 'white', 'Black', 'orange']


In [49]:
# Matthew
Matthew_list.append("green")
print(Matthew_list)

['blue', 'black', 'white', 'green']


In [50]:
test_Dictionary.update({'chicken':['cyan','turqouis']})

print(test_Dictionary)

NameError: name 'test_Dictionary' is not defined

In [51]:
test_Dictionary

NameError: name 'test_Dictionary' is not defined

In [52]:
test_Dictionary = {'Holly': ['green', 'pink', 'yellow', 'red', 'red'],
                  "Matthew": ['blue', 'black', 'white', 'green', 'green', 'green']}
test_Dictionary

{'Holly': ['green', 'pink', 'yellow', 'red', 'red'],
 'Matthew': ['blue', 'black', 'white', 'green', 'green', 'green']}

In [53]:
test_Dictionary.update({'ant':['dog','cat']})

In [54]:
test_Dictionary.update({'cat':['box']})

In [55]:
test_Dictionary.update({"dhrupadh": color_list})

print(test_Dictionary)

{'Holly': ['green', 'pink', 'yellow', 'red', 'red'], 'Matthew': ['blue', 'black', 'white', 'green', 'green', 'green'], 'ant': ['dog', 'cat'], 'cat': ['box'], 'dhrupadh': ['blue', 'red', 'green', 'white', 'Black', 'orange']}


In [56]:
test_Dictionary['Holly'] = 5
test_Dictionary

{'Holly': 5,
 'Matthew': ['blue', 'black', 'white', 'green', 'green', 'green'],
 'ant': ['dog', 'cat'],
 'cat': ['box'],
 'dhrupadh': ['blue', 'red', 'green', 'white', 'Black', 'orange']}

In [57]:
Color_Dictionary = {'Dhrupadh' : color_list}
Color_Dictionary

{'Dhrupadh': ['blue', 'red', 'green', 'white', 'Black', 'orange']}

### For loops, while loops, and if statements 



We will learn more about for loops in the next lesson. For now, we will use them to go through a list and print out each element.



In [58]:
print(my_list)

[1, 2, 3, 4, 5]


In [59]:
# Nolawi and Matthew have a look at this!
for number in my_list:
    print(number)

1
2
3
4
5


Next, we will look at how to make a list run a specific number of times.



In [60]:
for i in range(5): # range functions the same here as the list [0,1,2,3,4,5]
    print('i = ', i)

i =  0
i =  1
i =  2
i =  3
i =  4


In [61]:
print(list(range(10)))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]


In [62]:
color_list

['blue', 'red', 'green', 'white', 'Black', 'orange']

In [63]:
for i in range(10):
    print(color_list[i])

blue
red
green
white
Black
orange


IndexError: list index out of range

Next, we'll take a look at while loops. In general, you can make a while loop do anything that a for loop can do but with slightly different syntax, so if you find youself understanding while loops better than for loops, you can just focus on using while loops. 



In the block below, we will make a while loop that runs 5 times. For while loops, we can't specify how long they will run for ahead of time so its important for us to create an achievable exit condition. An exit condition is just the condition that will cause the code to stop running. This is checked every time, immediatly before the code runs or reruns. We want to make sure that this condition will eventually happen, otherwise the code will run until something crashes or we manually close it



In [64]:
i = 0
while i < 5:
    print("Hello World")
    i = i + 1

Hello World


Hello World
Hello World
Hello World
Hello World


Now for if statements. The if-elif-else statement is used to conditionally execute a statement or a block of statements. Conditions can be true or false, execute one thing when the condition is true, something else when the condition is false.



In [65]:
pan = 'cold'
if pan == 'hot':
    print('dont touch')

In [66]:
a = 1
b = 2
if a > b:
    print("a is greater than b")

We can add else statements to the above. An else statement is what will be run if the original statement is false.



In [67]:
a = 1
b = 2
if a > b:
    print("a is greater than b")
else:
    print("a is less than b")

a is less than b


Additionally, we can use elif statements to add additional conditions to the structure.



In [68]:
a == b

False

In [69]:
a != b

True

In [70]:
a = 1
b = 1
if a > b:
    print("a is greater than b")
elif a == b:
    print("a equals b")
else:
    print("b is less than a")

a equals b


Now its your turn. Either break up into 3 teams and have each team solve one of the blocks or solve them all together.



In the next block, create a for loop that counts from 0 to 10 and prints out each number. Additionally, if the number is less than 3, print out "This is a small number".



In [71]:
for i in range(3):
    print('hello world')
    if i == 2:
        print('hello world 2')

hello world
hello world
hello world
hello world 2


In [72]:
# Dhruv and Jayden
i=0

while i < 11:
    print(i)
    i = i + 1
    if i < 3:
        print("This is a small number")

0
This is a small number
1
This is a small number
2
3
4
5
6
7
8
9
10


In the next block, create a while loop that prints out all of the even numbers between 1 and 10. Additionally, if the number is between 5 and 9, print the number out a second time.



In [73]:
# Holly and Dhrupadh
i=2
while i < 10:
    print(i) # you have an issue with the brackets your are using woth print. for any build in function of method you are expected to use () instead of []
    i = i + 2 
    if i > 5 and i < 9:
        print(i)

2
4
6
6
8
8


In the next block, ask the user to input 3 items and add them all to a list. Then. create a loop that prints out each item that the user entered.



In [74]:
# Nolawi and Matthew
my_list = ["5" ,"6" ,"7"]
for number in my_list:
        print(number)

5
6
7


### Functions



Functions act like variables but instead of storing a value, they store lines of code. Below we can see how a function is created and used.



In [75]:
dictionary = {'Inconspicuous': ['something not visible.'],
             'Abnoxious': 'unpleasent.'}

dictionary

{'Inconspicuous': ['something not visible.'], 'Abnoxious': 'unpleasent.'}

In [76]:
dictionary['Inconspicuous']

['something not visible.']

In [77]:
dictionary['Inconspicuous'] = 'invisible'
dictionary

{'Inconspicuous': 'invisible', 'Abnoxious': 'unpleasent.'}

In [78]:
dictionary.update({'cat': 'animal'})
dictionary

{'Inconspicuous': 'invisible', 'Abnoxious': 'unpleasent.', 'cat': 'animal'}

In [79]:
team_details = {}
def team_members(name, email, state):
    team_details.update({"name": name, 'email': email, "state": state})
    return team_details

In [80]:
team_members(name = 'Ritum Singh', email = 'ritumsingh23@blah.com', state = 'New York')

{'name': 'Ritum Singh', 'email': 'ritumsingh23@blah.com', 'state': 'New York'}

In [81]:
team_members('Nolawi Bisrat', 'johndoe@yahoo,com','Texas')

{'name': 'Nolawi Bisrat', 'email': 'johndoe@yahoo,com', 'state': 'Texas'}

In [82]:
def my_first_function(): # Syntax for creating a function. def - Define
    print('Hello world')

In [83]:
my_first_function()

Hello world


Whenever the computer sees the function being used, it automatically runs the code stored inside of that function.



Additionally, functions can take in one or multiple values to use in their code, as we can see below.



In [84]:
def add_numbers(a, b, c):
    total = a + b + c
    print(total)

In [85]:
for_1 = add_numbers(1, 5, 3)

9


In [86]:
sum_123

NameError: name 'sum_123' is not defined

Finnally, functions can have a "return" statement. This is what the function sends back to the place it was called. You can think of functions like black boxes where the parameters in the parentheses are the input and the return statement is the output. This output can be saved to a variable to be used later. We will redefine the add_numbers function from above using a return statement to show this off.



In [87]:
def add_numbers(a, b, c):
    total = a + b + c
    return total

In [88]:
out = add_numbers(1, 2, 3)
out

6

Now its your turn! You can either work on each of the following challenges in teams of 2 or walk through each one as a group. In any case, it is recommended to look at them at a high level together so that everyone understands the concepts in each section.



In the block below, create a function that takes in 2 numbers and returns True if the product of the numbers is positive and False in all other cases.



In [89]:
# Nolawi, Holly
def add_numbers3(a, b):
    total = a * b
    if total <=0:
        return(False)  
    else:
        return(True)

In [90]:
add_numbers3 (0, 1) 
add_numbers3 (1,2)

True

In the block below, create a function that takes in a string and returns the string in reverse order. For example, if the input was "Hello" the output should be "olleH"



In [91]:
# Dhruv and Dhrupadh
def add_letters (total):
    return total [::-1]

In [92]:
add_letters('Ritum') # output should be mutiR

'mutiR'

In the block below, create a function that takes in a list and prints out each element 1 at a time. For example, if the input was ['Dog', 'Cat', 'Hamster'], the output should be

Dog

Cat

Hamster



In [93]:
# Matt and Jayden
def add_pets (rat, ant, bird):
    print(add_pets)


In [94]:
my_list = ["5" ,"6" ,"7"]
for number in my_list:
        print(number)

5
6
7


In [95]:
list_ritum = ['cat', 'dog', 'tiger']

In [96]:
def add_pets(rand):
    # 1. print the list
    # 2. apply for loop to iterate over each element of the above list
    for elements in rand:
        # 3. print each element
        print(elements)
        print("")
add_pets(list_ritum)

cat

dog

tiger



In [97]:
list_ritum
print(list_ritum)

['cat', 'dog', 'tiger']


In [98]:
# Holly
i=0
print(list_ritum[i])


cat


In [99]:
# Dhrupadh

In [100]:
# Dhruv

list_ritum.print(range(3))

AttributeError: 'list' object has no attribute 'print'

In [101]:
# Nolawi



In [102]:
def f(x, y, z):
    return x**2 + y + z

f(4, 5, 10)

31

# Modules \(Pandas and numpy\)

### Why are there Pandas in Python? What is numpy?

In the following section we will be covering modules. Above, we leaned about functions and the power that they have. Modules let us use functions that other people have created to solve problems that we commonly encounter \-\- you can think of this as standing on the shoulders of giants by being just lazy enough to want to write code over and over again. 

For example, if we find that we frequently have to get a random number, instead of coding that entire process every time, you could just import a function that either you or someone else created in the past. Basically, modules and importing lets us have access to the work of many other coders, making it a very powerful tool.



### Numpy \- For Scientific Computing in Python

Below, we will import the numpy module and use a few of its functions to show off this power. Numpy is a library which is coded outside of python, making it faster. It gives us access to better and more efficient lists

For any module you encounter, you should be prepared to <u>read the docs.</u> The "docs" are how we can learn to use each module, and you can find Numpy's here: [https://numpy.org/. ](https://numpy.org/)

**For using modules, you'll want to import them like so below.**



In [103]:
import numpy as np #we rename numpy to np so we don't have to type 5 letters every time.

With Numpy, we can make a list of zeros like this:



In [104]:
my_array = np.zeros((2,3)) # (2,3) is the shape of the array
my_array

array([[0., 0., 0.],
       [0., 0., 0.]])

Or a list of random decimal numbers like this:



In [105]:
np.random.rand(3,2) # we don't need to put the shape in braces this time

array([[0.54444754, 0.0883094 ],
       [0.032372  , 0.59704646],
       [0.31148723, 0.23137701]])

Just like regular variables, we can do operations on this list



In [106]:
my_array2 = my_array + 1
my_array3 = my_array2 * 2
print(my_array2)
print(my_array3)

[[1. 1. 1.]
 [1. 1. 1.]]
[[2. 2. 2.]
 [2. 2. 2.]]


**TODO:** Make an array from my\_array of all \-3's:



In [107]:
#make an array of all -3's


In [108]:
# Nolawi
ok_array = np.zeros ((2, 3))-3
ok_array

array([[-3., -3., -3.],
       [-3., -3., -3.]])

In [109]:
# Dhrupadh
dhrupadh_array = np.zeros((100,100))
dhrupadh_array2 = dhrupadh_array - 3
dhrupadh_array2

array([[-3., -3., -3., ..., -3., -3., -3.],
       [-3., -3., -3., ..., -3., -3., -3.],
       [-3., -3., -3., ..., -3., -3., -3.],
       ...,
       [-3., -3., -3., ..., -3., -3., -3.],
       [-3., -3., -3., ..., -3., -3., -3.],
       [-3., -3., -3., ..., -3., -3., -3.]])

In [110]:
# Holly
holly_array = np.zeros((3,3)) 
holly_array2 = holly_array - 3
print(holly_array2)

[[-3. -3. -3.]
 [-3. -3. -3.]
 [-3. -3. -3.]]


In [111]:
# Matt
matthew_array = np.zeros((8,8))
matthew_array2 = matthew_array - 3
matthew_array2

array([[-3., -3., -3., -3., -3., -3., -3., -3.],
       [-3., -3., -3., -3., -3., -3., -3., -3.],
       [-3., -3., -3., -3., -3., -3., -3., -3.],
       [-3., -3., -3., -3., -3., -3., -3., -3.],
       [-3., -3., -3., -3., -3., -3., -3., -3.],
       [-3., -3., -3., -3., -3., -3., -3., -3.],
       [-3., -3., -3., -3., -3., -3., -3., -3.],
       [-3., -3., -3., -3., -3., -3., -3., -3.]])

In [112]:
# Jayden
jayden_array = np.zeros((4,3)) -3
jayden_array

array([[-3., -3., -3.],
       [-3., -3., -3.],
       [-3., -3., -3.],
       [-3., -3., -3.]])

In [113]:
# Dhruv

dhruv_array = np.zeros ((2,3))-3
dhruv_array

array([[-3., -3., -3.],
       [-3., -3., -3.]])

### Pandas \- A Data Scientist's Best Friend

With numpy briefly explored above, we will now check out a little bit about pandas. Pandas is an awesome module that helps us deal with large amounts of data in an easy to understand way. Below we will look at some of its many functions

First, we'll have to import it. It is common practice to \`import pandas as pd\` but you are free to import it as you see fit.


In [114]:
import pandas as pd

Pandas works with objects called **DataFrames**. Not sure what that is? Read the docs: [https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.html.](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.html)

Or you can simply look below.


In [115]:
ritum_data = pd.DataFrame({'A': [1, 2, 3, 4, 5, 6], 'B': [4, 5, 6, 7, 8, 9], 'C': [7, 8, 9, 11, 12, 13]})
ritum_data

A  B   C
0  1  4   7
1  2  5   8
2  3  6   9
3  4  7  11
4  5  8  12
5  6  9  13

Our dataframe is pretty small so it's easy to show the whole thing in the output, but for larger dataframes it is important to only show a few of the rows so we don't have to scroll all over. To do this, we can use the df.head\(x\) function to show the first x rows of the dataframe or tail\(x\) to show the last x number of rows


In [116]:
ritum_data.head()

A  B   C
0  1  4   7
1  2  5   8
2  3  6   9
3  4  7  11
4  5  8  12

In [117]:
ritum_data.tail()

A  B   C
1  2  5   8
2  3  6   9
3  4  7  11
4  5  8  12
5  6  9  13

Alternatively you can look at just 1 row at a time by calling it similarly to a dictionary


In [118]:
ritum_data['A']

0    1
1    2
2    3
3    4
4    5
5    6
Name: A, dtype: int64

You can also get various details about the dataframe with the following functions.


In [119]:
# Gives you the names of all of the columns
ritum_data.columns

Index(['A', 'B', 'C'], dtype='object')

In [120]:
# Gives you the names of all the columns, the number of rows in that column and a brief description of the values stored in those columns
ritum_data.describe()

A         B          C
count  6.000000  6.000000   6.000000
mean   3.500000  6.500000  10.000000
std    1.870829  1.870829   2.366432
min    1.000000  4.000000   7.000000
25%    2.250000  5.250000   8.250000
50%    3.500000  6.500000  10.000000
75%    4.750000  7.750000  11.750000
max    6.000000  9.000000  13.000000

In [121]:
# Tells you more about what is stored in those columns
ritum_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6 entries, 0 to 5
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   A       6 non-null      int64
 1   B       6 non-null      int64
 2   C       6 non-null      int64
dtypes: int64(3)
memory usage: 272.0 bytes


**Next we will check out iterating through a dataframe.**


In [122]:
# Going through a row 1 value at a time
for i in ritum_data['A']:
    print(i)

1
2
3
4
5
6


In [123]:
# going through the entire dataframe 1 value at a time
print(50*"-")
for col_name in data.columns:
    for value in data[col_name]:
        print(value)
print(50*"-")

--------------------------------------------------


NameError: name 'data' is not defined